baseURL = "https://ushiro.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Greg Heiman Personal Website"

disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true       # This applies to Chroma too.
pygmentsUseClasses = true       # This applies to Chroma too.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+
      enableEmoji = true
      enableGitInfo = true
      canonifyURLs = true

      publishDir = "docs"

[Author]
  name = "Greg Heiman"

[Social]
  github = "Ushrio"

[Menu]
  [[Menu.Main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[Menu.Main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 12

[Params]
  description = "Thoughts, posts, notes, and random museings"
  sitename = "Greg Heiman Blog"
  github = "https://github.com/Ushiro"
  intro = ""
  footer = ""
  custom_css = ["css/style.css"]

  [[Params.source]]
    url = "https://github.com/Ushrio/ushiro.github.io" # Mandatory, used in hugo-bare-min-theme single.html, baseof.html
    org_dir = "content-org/"
    md_dir = "content/"