baseURL = "https://ushiro.github.io"
languageCode = "en-us"
title = "Greg Heiman Personal Website"

# Mon Dec 18 17:41:00 EST 2017 - kmodi
# Need the canonifyURLs to be true as the test site is
# served in a subdir of https://ox-hugo.scripter.co/ ->
# https://ox-hugo.scripter.co/test/ So links like /images/foo.png
# won't work.. as /images/foo.png would be tried to be searched
# directly under https://ox-hugo.scripter.co/ instead of under
# https://ox-hugo.scripter.co/test/
canonifyURLs = true

enableEmoji = true
enableGitInfo = true

disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true       # This applies to Chroma too.
pygmentsUseClasses = true       # This applies to Chroma too.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+

[Taxonomies]
  category = "categories" # SINGULAR = "PLURAL"
  tag = "tags"

[Author]
  name = "Greg Heiman"

[Social]
  github = "Ushrio"

[Params]
  description = "Personal website with blogs and musings"
  intro = ""
  footer = ""
  custom_css = ["css/style.css"]
  [Params.source]
    url = "https://github.com/Ushrio/ushrio.github.io" # Mandatory, used in hugo-bare-min-theme single.html, baseof.html
    org_dir = "site/content-org"
    md_dir = "site/hugo/content/posts"