baseURL = "https://ushrio.github.io/heiman.dev/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Greg Heiman Personal Website"

disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true       # This applies to Chroma too.
pygmentsUseClasses = true       # This applies to Chroma too.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+
      enableEmoji = true
      enableGitInfo = true
      canonifyURLs = true

      publishDir = "docs"

[Menu]
  [[Menu.Main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[Params]
  description = "Thoughts, posts, notes, and random museings"
  sitename = "Greg Heiman Blog"
  author = "Greg Heiman"
  github = "https://github.com/Ushiro"